name: Car Racing Game

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозиторій
        uses: actions/checkout@v3

      - name: Встановлення Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Встановлення залежностей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Запуск тестів (з HTML-звітом)
        run: |
          mkdir -p reports/tests
          pytest --html=reports/tests/report.html --self-contained-html

      - name: Лінтінг з flake8
        run: |
          mkdir -p reports/lint
          flake8 src/ --format=html --htmldir=reports/lint

      - name: Завантаження артефактів (звіти)
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports

