name: CI/CD Pipeline for CarRacing Game

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Клон репозиторію
        uses: actions/checkout@v3

      - name: Встановлення Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Встановлення залежностей
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Перевірка встановлених пакетів (debug)
        run: pip list

      - name: Лінтінг з Flake8 (HTML-звіт)
        run: |
          mkdir -p reports/lint
          flake8 src/ --format=html --htmldir=reports/lint || true

      - name: Тестування з Pytest (HTML-звіт)
        run: |
          mkdir -p reports/tests
          pytest --html=reports/tests/report.html --self-contained-html || true

      - name: Завантаження звітів як артефакти
        uses: actions/upload-artifact@v4
        with:
          name: test-and-lint-reports
          path: reports


